[package]
name = "russetair-battleship"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

pollster = "*"

hecs = "0.9"

winit = "0.27"
wgpu = "0.14"
uv = { package = "ultraviolet", versino = "0.9" }