[package]
name = "russetair-battleship"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bytemuck = "1"

hecs = "0.9"

winit = "0.27"
vulkano = "0.32"
vulkano-shaders = "0.32"
vulkano-win = "0.32"

uv = { package = "ultraviolet", versino = "0.9" }