= Russetair Battleship

== Style Guide

Use WebKit style to cope with the extremely long names of the Vulkan API. Structs follow the `typedef {} CamelCase` convention for the above reason and for compatibility with flecs.

All identifiers use `camelCase`, while data types use `PascalCase`. What act as a constructor follow `_PascalCase` or `newPascalCase`. Private identifiers start with underscore.

ECS entities spawn with `spawnEntityName` and end with `cleanupEntityName`. `setupSubsystem` refers to when only components are updated.
If entity is supposed to be "system-level", such as graphics system, vulkan system, etc, use `createEntityName` instead.

== Roadmap

- [ ] Vulkan draw anything
- [ ] Sector and chunk 2D debugger
- [ ] Terrain 3D and spectator

=== Vulkan

- [x] Creates instance
- [x] Enumerates physical devices and store as entities
- [x] Create logical device
- [x] Create surface
- [x] Create queues
- [x] Create swapchain
- [x] Refactor with Prefabs
- [ ] Refactor ECS declarations
- [ ] Clear screen render pass
- [ ] Triangle
- [ ] Select best device instead of first device
- [ ] Proper cleanup

=== 2D Debugger

- [ ] Just make a separate render pass
- [ ] Add MVP transform (after 3D)

=== Terrain and Spectator

- [ ] Render terrain with displacement
- [ ] Spectator control and camera movement
- [ ] 2D debugger overlay
- [ ] Terrain texture and material
- [ ] Terrain load from SQLite3 file

=== Models

- [ ] gltf model loading
- [ ] Player control
