package hw762.russetair

import hw762.russetair.gfx.Window
import hw762.russetair.vk.Instance
import org.lwjgl.glfw.GLFW.glfwInit

/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

fun main() {
    val window = Window("Russetair Battleship")
    val instance = Instance(true)
}
